trigger:
  tags:
    include:
      - "*.*.*"
  branches:
    include:
      - main

pool:
  name: "Azure Pipelines"

jobs:
  - job: Push
    timeoutInMinutes: 10

    workspace:
      clean: all

    steps:
      - checkout: self
        clean: true
        fetchDepth: 0
        fetchTags: true

      - task: UseDotNet@2
        displayName: "Use .NET 6 SDK"
        inputs:
          packageType: sdk
          version: 6.0.x

      - task: PowerShell@2
        displayName: "Restore, build, test, pack"
        inputs:
          targetType: "filePath"
          filePath: "Build.ps1"

      - task: NuGetAuthenticate@1
        displayName: "NuGet authenticate"

      - task: NuGetCommand@2
        displayName: "Push NuGet package to internal feed"
        inputs:
          command: push
          publishVstsFeed: "gsoft"
          packagesToPush: ".output/*.nupkg"
          allowPackageConflicts: false
